cask "font-jetbrains-mono-nerd-font"
cask "font-microsoft-office"
cask "font-microsoft-aptos"
cask "font-arial"
cask "font-arial-black"
cask "font-courier-new"
cask "font-times-new-roman"
cask "font-georgia"
